"""creo tabla de suscripción premium

Revision ID: 948dfd192e5d
Revises: 
Create Date: 2025-04-24 15:37:04.329060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948dfd192e5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_subscription', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_foreign_key(None, 'premium_subscription', ['id_subscription'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id_subscription')

    # ### end Alembic commands ###
